services:
  postgres:
    image: postgres:17.3-alpine3.20
    container_name: staffing-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: staffing
      POSTGRES_USER: staffing-user
      POSTGRES_PASSWORD: changeMe
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U staffing-user -d staffing"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  liquibase:
    image: liquibase/liquibase:4.31
    container_name: staffing-liquibase
    volumes:
      - ./db:/liquibase/db
    command: 
      - --defaults-file=/liquibase/db/changelog/liquibase.properties
      - update
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: staffing_postgres_data